### ISSUE TITLE
Pressing The Console Key Leads to Crash

### ISSUE THREAD

**Issue by snajdovski** [shekeru/dotka-cheats#5]
With the help in the comments by the community, I managed to fix the cheat and it seems to work again but there is a major problem.
When opening the Console, there is an instant crash, after looking in the code I saw a function that disables the console, don't know why, but I commented out that function still I get a crash.

Is there any way I can log the crash and see where it goes wrong?

**Comment by molodoydoto** [comment]
yeah :D
